version: "3.8"
services:
  frontend:
    container_name: WitPaKul_FrontEnd
    build: .
    image: registry.gitlab.com/witpakul/witpakul-ii-frontend:develop

networks:
   default:
     external:
         name: witpakul_network
